//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chronos.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chronos.Core.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature code.
        /// </summary>
        internal static string FeatureRulesConstants_TitleVariables_FeatureCode_Description {
            get {
                return ResourceManager.GetString("FeatureRulesConstants.TitleVariables.FeatureCode.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CDB, ABP....
        /// </summary>
        internal static string FeatureRulesConstants_TitleVariables_ProductCode_Description {
            get {
                return ResourceManager.GetString("FeatureRulesConstants.TitleVariables.ProductCode.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;
        ///&lt;div&gt;
        ///&lt;b&gt;Assumptions &amp; Limitations &amp; Dependencies &lt;/b&gt;
        ///&lt;/div&gt;
        ///&lt;div&gt;None&lt;/div&gt;
        ///&lt;br/&gt;
        ///&lt;div&gt;
        ///&lt;b&gt;Acceptance Criteria&lt;/b&gt;
        ///&lt;/div&gt;
        ///&lt;br/&gt;
        ///&lt;div&gt;
        ///&lt;b&gt;Implementation Details&lt;/b&gt;
        ///&lt;/div&gt;
        ///&lt;div&gt;None&lt;/div&gt;
        ///&lt;/div&gt;.
        /// </summary>
        internal static string FeatureRulesConstants_TitleVariables_StoryAcceptanceCriteria {
            get {
                return ResourceManager.GetString("FeatureRulesConstants.TitleVariables.StoryAcceptanceCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;
        ///&lt;div&gt;As&lt;/div&gt;
        ///&lt;div&gt;I Want&lt;/div&gt;
        ///&lt;div&gt;So that&lt;/div&gt;
        ///&lt;br/&gt;
        ///&lt;div&gt;
        ///&lt;b&gt;Additional Information&lt;/b&gt;
        ///&lt;/div&gt;
        ///&lt;div&gt;None&lt;/div&gt;
        ///&lt;br/&gt;
        ///&lt;div&gt;
        ///&lt;b&gt;Glossary&lt;/b&gt;
        ///&lt;/div&gt;
        ///&lt;div&gt;None&lt;/div&gt;
        ///&lt;/div&gt;.
        /// </summary>
        internal static string FeatureRulesConstants_TitleVariables_StoryDescription {
            get {
                return ResourceManager.GetString("FeatureRulesConstants.TitleVariables.StoryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure DevOps Id.
        /// </summary>
        internal static string FeatureRulesConstants_TitleVariables_StoryId_Description {
            get {
                return ResourceManager.GetString("FeatureRulesConstants.TitleVariables.StoryId.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial name from estimate.
        /// </summary>
        internal static string FeatureRulesConstants_TitleVariables_StoryName_Description {
            get {
                return ResourceManager.GetString("FeatureRulesConstants.TitleVariables.StoryName.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begins from 01.
        /// </summary>
        internal static string FeatureRulesConstants_TitleVariables_StoryOrderNumber_Description {
            get {
                return ResourceManager.GetString("FeatureRulesConstants.TitleVariables.StoryOrderNumber.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial name from estimate.
        /// </summary>
        internal static string FeatureRulesConstants_TitleVariables_TaskName_Description {
            get {
                return ResourceManager.GetString("FeatureRulesConstants.TitleVariables.TaskName.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begins from 01.
        /// </summary>
        internal static string FeatureRulesConstants_TitleVariables_TaskOrderNumber_Description {
            get {
                return ResourceManager.GetString("FeatureRulesConstants.TitleVariables.TaskOrderNumber.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Lead And support.
        /// </summary>
        internal static string FeatureRulesConstants_TitleVariables_ZeroStoryName_Description {
            get {
                return ResourceManager.GetString("FeatureRulesConstants.TitleVariables.ZeroStoryName.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00.
        /// </summary>
        internal static string FeatureRulesConstants_TitleVariables_ZeroStoryOrderNumber_Description {
            get {
                return ResourceManager.GetString("FeatureRulesConstants.TitleVariables.ZeroStoryOrderNumber.Description", resourceCulture);
            }
        }
    }
}
